### ISSUE TITLE
No module name jwt

### ISSUE THREAD

**Issue by wellcheng** [pelauimagineering/apple-music-token-generator#8]
When I execute this command, will show:
```shell
Traceback (most recent call last):
  File "music_token.py", line 6, in <module>
    import jwt
ImportError: No module named jwt
```

I am sure , i installed everything on readme page.

``` shell
➜  apple-music-token-generator git:(master) ✗ which pip                                                                                                                                         
/usr/local/bin/pip

➜  apple-music-token-generator git:(master) ✗ which python                                                                                                                                     
/usr/bin/python

Requirement already satisfied: pyjwt in /usr/local/lib/python2.7/site-packages (1.7.1)
```

**Comment by pelauimagineering** [comment]
Perhaps your setup requires you to use the explicit name of the module as such:

import **pyjwt** 

?

**Comment by azeemohd786** [comment]
I have the same issue, does anyone have a solution?
```
Traceback (most recent call last):
  File "music_token.py", line 6, in <module>
    import jwt
ImportError: No module named jwt
```

**Comment by azeemohd786** [comment]
I have reinstalled 
`sudo pip install pyjwt`

error went out...

**Comment by hellokurt** [comment]
the same issue :(

**Comment by mtroskot** [comment]
The most likely is that you have different python installations and they are nit matching.
Try to run it with `python3 music_token.py`
